export const TransactionData = [
  {
    index: 0,
    type: "Deposit",
    currency: "Ethereum",
    amountCrypto: 0.226,
    amountUSD: 50.25,
    changeCollateral: null,
    iconImageSource: require("../assets/icons/Coins/1.png"),
  },
  {
    index: 1,
    type: "Borrowed",
    currency: "Aave",
    amountCrypto: 6.21,
    amountUSD: 2914.16,
    changeCollateral: null,
    iconImageSource: require("../assets/icons/Coins/2.png"),
  },
  {
    index: 2,
    type: "Collateral Change",
    currency: "Ethereum",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: { from: "No", to: "Yes" },
    iconImageSource: require("../assets/icons/Coins/3.png"),
  },
  {
    index: 3,
    type: "Deposit",
    currency: "Compound",
    amountCrypto: 2.14,
    amountUSD: 1182.32,
    changeCollateral: null,
    iconImageSource: require("../assets/icons/Coins/4.png"),
  },
  {
    index: 4,
    type: "Collateral Change",
    currency: "Ethereum",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: { from: "Yes", to: "No" },
    iconImageSource: require("../assets/icons/Coins/5.png"),
  },
  {
    index: 5,
    type: "Deposit",
    currency: "Sushiswap",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: null,
    iconImageSource: require("../assets/icons/Coins/5.png"),
  },
  {
    index: 6,
    type: "Borrowed",
    currency: "Sushiswap",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: null,
    iconImageSource: require("../assets/icons/Coins/5.png"),
  },
];
