export const TransactionData = [
  {
    index: 0,
    type: "Deposit",
    currency: "Ethereum",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: null,
  },
  {
    index: 1,
    type: "Borrowed",
    currency: "Mana",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: null,
  },
  {
    index: 2,
    type: "Collateral Change",
    currency: "Ethereum",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: { from: "No", to: "Yes" },
  },
  {
    index: 3,
    type: "Deposit",
    currency: "Ethereum",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: null,
  },
  {
    index: 4,
    type: "Collateral Change",
    currency: "Ethereum",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: { from: "Yes", to: "No" },
  },
  {
    index: 5,
    type: "Deposit",
    currency: "Ethereum",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: null,
  },
  {
    index: 6,
    type: "Borrowed",
    currency: "Ethereum",
    amountCrypto: 0.0025,
    amountUSD: 4.132,
    changeCollateral: null,
  },
];
